"""Database creation

Revision ID: 2b12ec7d4cd1
Revises: 
Create Date: 2024-09-18 21:31:28.370127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b12ec7d4cd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', name='levels'), nullable=False),
    sa.Column('question', sa.String(length=400), nullable=False),
    sa.Column('correct_id', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=False),
    sa.Column('datetime_shown', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('options',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'option_id')
    )
    op.create_index('ix_question_option', 'options', ['question_id', 'option_id'], unique=True)

    op.create_foreign_key(
    'fk_correct_option_id', 'questions', 'options',
    ['id', 'correct_id'], ['question_id', 'option_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_option', table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
